# Generated by Django 4.2.13 on 2026-07-30 16:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("categories", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Product",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("slug", models.SlugField(max_length=280, unique=True)),
                ("sku", models.CharField(max_length=50, unique=True)),
                (
                    "brand",
                    models.CharField(default="NexCart Select", max_length=100),
                ),
                ("short_description", models.CharField(blank=True, max_length=500)),
                ("description", models.TextField()),
                ("price", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "discount_price",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                ("stock", models.PositiveIntegerField(default=10)),
                (
                    "primary_image_url",
                    models.URLField(
                        help_text="Main product display image", max_length=500
                    ),
                ),
                ("is_featured", models.BooleanField(default=False)),
                ("is_trending", models.BooleanField(default=False)),
                ("is_best_seller", models.BooleanField(default=False)),
                ("is_flash_sale", models.BooleanField(default=False)),
                ("flash_sale_end", models.DateTimeField(blank=True, null=True)),
                ("rating_avg", models.FloatField(default=4.8)),
                ("rating_count", models.PositiveIntegerField(default=12)),
                ("specifications", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="products",
                        to="categories.category",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="ProductImage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("image_url", models.URLField(max_length=500)),
                ("alt_text", models.CharField(blank=True, max_length=200)),
                ("order", models.IntegerField(default=0)),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="gallery_images",
                        to="products.product",
                    ),
                ),
            ],
            options={
                "ordering": ["order"],
            },
        ),
    ]
